import { getEditorHtml } from '../src';

const data = {
  root: {
    children: [
      {
        children: [{ detail: 0, format: 0, mode: 'normal', style: '', text: 'Hi there,', type: 'text', version: 1 }],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: '5bFa',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Handuo here, initiator of ',
            type: 'text',
            version: 1,
          },
          {
            children: [{ detail: 0, format: 0, mode: 'normal', style: '', text: 'Copus', type: 'text', version: 1 }],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'link',
            version: 1,
            rel: 'noreferrer',
            target: null,
            title: null,
            url: 'https://www.copus.io/work/52c7ee85f1a34dee9ce9b6c29c830028',
          },
          { detail: 0, format: 0, mode: 'normal', style: '', text: ' and', type: 'text', version: 1 },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' the protocol powering the innovation network',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'link',
            version: 1,
            rel: null,
            target: null,
            title: null,
            url: 'https://fractopus.net/',
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ". I'm here to introduce some of Copus's key features and explain our team’s design choices.",
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'vLDj',
      },
      {
        children: [
          {
            detail: 0,
            format: 1,
            mode: 'normal',
            style: '',
            text: 'If you prefer a video intro, here it is:',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 1,
        textStyle: '',
        id: 'jYMJ',
      },
      {
        children: [],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: '3r6W',
      },
      {
        children: [
          {
            src: 'https://static.copus.io/images/client/202410/prod/867efbda4c2b8bafa78fb8715b59d74f.mov',
            type: 'video',
            autoplay: false,
            controls: true,
            height: 0,
            width: 0,
            version: 1,
          },
        ],
        direction: null,
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'oASR',
      },
      {
        children: [],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'nc30',
      },
      {
        children: [{ detail: 0, format: 1, mode: 'normal', style: '', text: 'Why', type: 'text', version: 1 }],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'heading-x',
        version: 1,
        tag: 'h3',
        id: 'pTIP',
      },
      {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'We first started around three years ago as a collaborative science-fiction project.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'link',
            version: 1,
            rel: 'noreferrer',
            target: null,
            title: null,
            url: 'https://www.copus.io/work/01acce79be524f389655b9658fd3568b',
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' We experienced, first-hand, ',
            type: 'text',
            version: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'some fundamental issues with the current copyright system',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'link',
            version: 1,
            rel: 'noreferrer',
            target: null,
            title: null,
            url: 'https://www.copus.io/work/fd01655ffd8a46a5b4e64d7e78398e70',
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: '. Long story short, the current system benefits corporations and business-oriented individuals, rather than creators.',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'b6Wj',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'We wanted to change that.',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'xch4',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'As creators ourselves, we understand what creators need most: for our works to be seen while we can support a creative life.',
            type: 'text',
            version: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' Currently, the most open content distribution channel—the internet—does not support this, as it is gated by major platforms (YouTube, Amazon, Medium, etc.)',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'link',
            version: 1,
            rel: 'noreferrer',
            target: null,
            title: null,
            url: 'https://www.copus.io/work/89171ed495c340658524fa964d7d9ec4',
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: " Creators are forced to follow the platforms' rules: even while we reinforce monopolies with our content, we are exploited by them taking a portion of our earnings.",
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'HR1i',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'This, too, must be changed.',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'wMGY',
      },
      {
        children: [],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'aPAo',
      },
      {
        children: [{ detail: 0, format: 1, mode: 'normal', style: '', text: 'How', type: 'text', version: 1 }],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'heading-x',
        version: 1,
        tag: 'h3',
        id: 'GdIi',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'We needed a new system and new tools that prioritized creators over "copyright owners" and monopolistic platforms. So, we came up with',
            type: 'text',
            version: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' the concept of an "inspiration network"',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'link',
            version: 1,
            rel: 'noreferrer',
            target: null,
            title: null,
            url: 'https://www.copus.io/work/ca9960ae05c74bf3add7e01e794fc136',
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' where creators support each other by sharing exposure and earnings. The key ideas are:',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'yzSK',
      },
      {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '- Instead of relying on platform algorithms to showcase your work, you decide where it is shown.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '- Instead of giving part of your earnings to platforms, you share them with your fellow creators, just as they share with you.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 2,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'list-x',
        version: 1,
        listType: 'bullet',
        start: 1,
        tag: 'ul',
        id: 'FmOa',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'This is a peer-to-peer network, collaboratively owned and governed by all creators and audiences involved.',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'hFvQ',
      },
      {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: 'In practice, a creator can address any URI (URL) online as a "Source" for their piece by sharing percentages of the piece\'s future revenue with those sources. This way, the piece can be showcased on the "Inspiration Source\'s" webpage as their "Branch," gaining exposure.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'link',
            version: 1,
            rel: 'noreferrer',
            target: null,
            title: null,
            url: 'https://www.copus.io/work/a3c4a57766624c6c8d0c36799c3d9c30',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 1,
        textStyle: '',
        id: 'tCdR',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'What does this look like? Let’s say you are paid $10 and your content credits 10% to two sources (20% total). The sources will earn ($10*10%) – ',
            type: 'text',
            version: 1,
          },
          {
            children: [{ detail: 0, format: 0, mode: 'normal', style: '', text: '$0.01', type: 'text', version: 1 }],
            direction: null,
            format: '',
            indent: 0,
            type: 'link',
            version: 1,
            rel: 'noreferrer',
            target: null,
            title: null,
            url: 'https://www.copus.io/work/4c9f2444987641aa896487be85e25de0',
          },
          { detail: 0, format: 0, mode: 'normal', style: '', text: ' = $0.99. Your ', type: 'text', version: 1 },
          { detail: 0, format: 2, mode: 'normal', style: '', text: 'active ', type: 'text', version: 1 },
          { detail: 0, format: 0, mode: 'normal', style: '', text: 'revenue will be $8.', type: 'text', version: 1 },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'hz7W',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'However, in exchange, when a user is browsing and finds your content’s sources, your content will get more exposure—your work appears as a branch which users can trust (the content everyone sees is always hand-picked by a human, not an algorithm).',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'k2xv',
      },
      {
        children: [
          { detail: 0, format: 0, mode: 'normal', style: '', text: 'Additionally, your ', type: 'text', version: 1 },
          { detail: 0, format: 3, mode: 'normal', style: '', text: 'total', type: 'text', version: 1 },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' revenue is not just $8. Your branches continue to stream passively in exchange for exposure. Just by inspiring, you are earning!',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'g4H7',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'You can publish this type of "connected content" on Copus or connect content you\'ve published anywhere online to the network through',
            type: 'text',
            version: 1,
          },
          {
            children: [
              { detail: 0, format: 0, mode: 'normal', style: '', text: ' ', type: 'text', version: 1 },
              {
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: 'the Copus browser extension',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'link',
            version: 1,
            rel: null,
            target: null,
            title: null,
            url: 'https://chromewebstore.google.com/detail/copus/nmeambahohkondggcpdomcbgdalnkmcb',
          },
          { detail: 0, format: 1, mode: 'normal', style: '', text: '.', type: 'text', version: 1 },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'I1vh',
      },
      {
        children: [],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 1,
        textStyle: '',
        id: 'weW0',
      },
      {
        children: [
          {
            detail: 0,
            format: 1,
            mode: 'normal',
            style: '',
            text: 'What makes Copus important?',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'heading-x',
        version: 1,
        tag: 'h3',
        id: 'wvqy',
      },
      {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Emerging content and creators have a new way to build an audience—by addressing their inspirations and opening doors to existing communities. ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Inspiring content and creators are provided a constant stream of income—your inspiration offspring generate revenue for you when they earn. ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 2,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Your authorship of the content is secured without the need for copyright—everyone you inspire secures your ownership for you. ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 3,
          },
          {
            children: [
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Platform fees for creators are reduced from 8-50%+ to less than $0.01.',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'link',
                version: 1,
                rel: 'noreferrer',
                target: null,
                title: null,
                url: 'https://www.copus.io/work/4c9f2444987641aa896487be85e25de0',
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 4,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Copus is a public good (an open database) that is collaboratively owned by the people who build and use it.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 5,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'list-x',
        version: 1,
        listType: 'number',
        start: 1,
        tag: 'ol',
        id: 'z1HU',
      },
      {
        children: [],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'rd8j',
      },
      {
        children: [
          { detail: 0, format: 1, mode: 'normal', style: '', text: 'What can I do? ', type: 'text', version: 1 },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'heading-x',
        version: 1,
        tag: 'h3',
        id: 'tU5o',
      },
      {
        children: [
          {
            detail: 0,
            format: 1,
            mode: 'normal',
            style: '',
            text: 'If you want to create something today',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ', connect your content to the inspiration network by publishing on Copus or linking through',
            type: 'text',
            version: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' the Copus browser extension',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'link',
            version: 1,
            rel: null,
            target: null,
            title: null,
            url: 'https://chromewebstore.google.com/detail/copus/nmeambahohkondggcpdomcbgdalnkmcb',
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' if you prefer to publish elsewhere. Either way, you are supporting your fellow creators rather than the platforms! Unlock new ways to promote and monetize your work while significantly lowering third-party cuts from your earnings. ',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: '3s7B',
      },
      {
        children: [
          { detail: 0, format: 1, mode: 'normal', style: '', text: 'If you want to explore', type: 'text', version: 1 },
          { detail: 0, format: 0, mode: 'normal', style: '', text: ',', type: 'text', version: 1 },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' the Copus browser extension',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'link',
            version: 1,
            rel: null,
            target: null,
            title: null,
            url: 'https://chromewebstore.google.com/detail/copus/nmeambahohkondggcpdomcbgdalnkmcb',
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' unlocks a new layer of your internet experience. When the little Fractopus speaks to you, the page you are viewing may have some "Branches" for you to dive into. This is a great way to break through your information bubble. Find your rabbit hole!',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'kwTk',
      },
      {
        children: [
          {
            detail: 0,
            format: 1,
            mode: 'normal',
            style: '',
            text: 'If you feel inspired while browsing',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ', simply hit the "Branch it" button and start creating or use the "Add sources" function in your editing window.',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 1,
        textStyle: '',
        id: '5fTp',
      },
      {
        children: [],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: '7vo6',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Thank you for listening to our team of idealists’ dream—we sincerely believe that ',
            type: 'text',
            version: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'everyone is creative and that people will share resources to build a system that benefits each other',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'link',
            version: 1,
            rel: 'noreferrer',
            target: null,
            title: null,
            url: 'https://www.copus.io/work/9b6de128afaa4d23803ea2c0e96e31a0',
          },
          { detail: 0, format: 0, mode: 'normal', style: '', text: '.', type: 'text', version: 1 },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'G8Mu',
      },
      {
        children: [],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'InwP',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: "Let's connect creativity and make it happen!",
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph-x',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: 'qR0o',
      },
    ],
    direction: 'ltr',
    format: '',
    indent: 0,
    type: 'root',
    version: 1,
  },
};

console.log(await getEditorHtml(JSON.stringify(data)));
